### ISSUE TITLE
[CHORE] 최근 생성된 리스트 조회

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#119]
## 📌Issue
최근 생성된 리스트 조회

## 📝To-Do
- [ ] 함꼐 패킹리스트인 경우 함께-나의 연걸 id 주기
- [ ] responseBody의 url `alone?id=1` 형식으로 바꾸기
- [ ] 최근 리스트 조회할 때 is_deleted = false 조건 추가
