### ISSUE TITLE
[CHORE] transaction관련 수정 사항 및 service의 필요없는 try-catch문 제거

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#155]
## 📌Issue
transaction관련 수정 사항 및 service의 필요없는 try-catch문 제거

## 📝To-Do
- [ ] transaction] 관련 수정사항
- [ ] service의 필요없는 try-catch문 제거
- [ ] controller의 catch문에 console.log(error) 없는 경우 추가
