### ISSUE TITLE
[FEAT] 닉네임, 프로필 등록 API의 requestBody에 path 추가

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#166]
## 📌Issue
닉네임, 프로필 등록 API의 requestBody에 path 추가

## 📝To-Do
- [x] requestBody에 path 추가
- [x] userDB path column 추가
- [x] path도 DB에 저장하도록 service 수정
