### ISSUE TITLE
[FEAT] 폴더 안 함께 패킹리스트 조회

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#39]
## 📌Issue
폴더 안 함께 패킹리스트 조회

## 📝To-Do
- [x] folderId로 현재 폴더 정보 조회
- [x] userId로 user가 가지고 있는 함께 패킹리스트 폴더들 조회
- [x] 현재 폴더 안의 리스트 정보들 조회
- [x] 현재 폴더 안 총 리스트 수 count
