### ISSUE TITLE
[FEAT] 1주차 API 배포 전 수정사항 

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#42]
## 📌Issue
- 1주차 API 배포 전 수정사항

## 📝To-Do
- [x] router에 auth 추가
- [x] controller에서 client undefined일 때 처리
- [x] responseBody 체크
- [x] API 명세서 보면서 빠진 부분 체크
- [x] cors 처리
