### ISSUE TITLE
[FEAT] 랜딩 페이지 사용자 등록

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#43]
## 📌Issue
랜딩페이지 사용자 등록

## 📝To-Do
- [x] 랜딩 route, controller, service 구현
- [x] 필요한 값 없을 때 에러처리
- [x] 핸드폰 번호 중복 막기
