### ISSUE TITLE
[CHORE] 1주차, 2주차 API 수정사항

### ISSUE THREAD

**Issue by hyeon-z** [Team-Packman/Packman-Server-Release#81]
## 📌Issue
1주차, 2주차 API 수정사항

## 📝To-Do
- [x] departureDate 형식 YYYY.MM.DD -> YY-MM-DD로 변경
- [x] 함께, 혼자 패킹리스트 상세조회  reponseBody group 배열 -> 객체로 변경
- [x] 최근 생성된 리스트 조회 500에러 수정
